language: node_js

sudo: true

env:
  - NODE_ENV=production CI=true

node_js:
  - "10"

services:
  - docker

before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
   - echo "Skip build"
#  - yarn build
#  - yarn test:coverage
#  - cp ./build/client/index.html ./build/client/200.html

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/client
    domain: ergo-explorer.surge.sh

  - provider: script
    on:
      all_branches: true
    script: bash .travis/heroku_docker

after_success:
  - codecov
