language: node_js

env:
  - NODE_ENV=production CI=true

node_js:
  - "10"

script:
  - yarn build
  - yarn test:coverage
  - cp ./build/client/index.html ./build/client/200.html
  - docker-compose build

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/client
    domain: ergo-explorer.surge.sh

  - provider: script
    script: bash .travis/heroku_docker

after_success:
  - codecov
