version: '3.6'

services:

  ergo-explorer-node:
      container_name: ergo-explorer-node
      build:
        context: .
      volumes:
        - ${REACT_APP_APP_CONFIG:-./client/public/app.config.js}:/usr/src/app/build/client/app.config.js

  ergo-explorer-nginx:
    image: nginx:stable-alpine
    container_name: ergo-explorer-nginx
    depends_on:
      - ergo-explorer-node
    ports:
      - '80:80'
    volumes:
      - ./config/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
